version: '3.8'

services:
  nginx:
    image: nuralmumit/eqs-qrc-nginx-img:v1
    container_name: eqs-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - eqs-network

  frontend:
    image: nuralmumit/eqs-qrc-frontend-img:latest
    container_name: eqs-frontend
    restart: always
    environment:
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE}
    networks:
      - eqs-network

  backend:
    image: nuralmumit/eqs-qrc-backend-img:latest
    container_name: eqs-backend
    restart: always
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - eqs-network

  db:
    image: mysql:8.0
    container_name: eqs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eqs-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: eqs-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_HTTPS: 1
      PMA_TRUSTED_PROXIES: 0.0.0.0/0
    networks:
      - eqs-network

networks:
  eqs-network:
    driver: bridge

volumes:
  mysql_data: