export const adminAuthRoutes = {
  commonPaths: ["/registration"],
  authPaths: [
    "/admin/sign-in",
    "/admin/sign-up",

    // Registration related paths
    "/registration/otp",
  ],
  protectedPaths: [
    "/admin/add-student",
    "/admin/settings",
    "/admin/attendance",
    "/admin/competition",
    "/admin/profile",
    "/admin/profile/update",
    "/admin/registration/token",
    "/admin/settings",
    "/admin/dashboard",
    "/admin/profile",
    "/admin/report-issues",
    "/admin/submit-viva-result",
    "/admin/verify-registration",
    "/admin/training-attendance",
    "/admin/training-attendance-view",
    "/admin/training-dates",
    "/admin/training-id-card",
    "/admin/final-contest-id-card",
    "/admin/final-round-id-card",
    "/admin/final-round-mark-sheet",
    "/admin/final-confirmation",
    "/admin/final-attendance",
    "/admin/final-attendance-view",
    "/admin/view-registrations",
    "/admin/create-admin",
    "/x",
  ],
};
